language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
    - /^.*-feature$/
    - /^.*-release-candidate$/
cache:
  directories:
    - $HOME/.npm
